name: CI

on: [push,pull_request]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          activate-environment: pypolca
          environment-file: build/environment.yaml
          auto-activate-base: false
          miniforge-variant: Mambaforge
          channels: conda-forge,bioconda,defaults
          channel-priority: strict
          auto-update-conda: true

      - name: Install project
        shell: bash -l {0}
        run: |
          mamba install python=${{ matrix.python-version }}
          just install
      - name: Check formatting
        shell: bash -l {0}
        run: just check-fmt
      - name: Test and generate coverage report with pytest
        shell: bash -l {0}
        run: just test-ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      

